// <auto-generated />
using System;
using AutoTuner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTuner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117154243_AddZeroToHundredToCar")]
    partial class AddZeroToHundredToCar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoTuner.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DrivingStyle")
                        .HasColumnType("int");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Torque")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<double>("ZeroToHundred")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volkswagen",
                            Drivetrain = "FWD",
                            DrivingStyle = 0,
                            EngineType = "2.0 TSI",
                            HorsePower = 245,
                            Model = "Golf GTI",
                            Torque = 370,
                            UserId = "b8c7553d-0b10-454f-8d1c-6cbf165168ff",
                            Weight = 1440,
                            Year = 2021,
                            ZeroToHundred = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            Drivetrain = "RWD",
                            DrivingStyle = 1,
                            EngineType = "3.0 Twin Turbo",
                            HorsePower = 473,
                            Model = "M3",
                            Torque = 550,
                            UserId = "b8c7553d-0b10-454f-8d1c-6cbf165168ff",
                            Weight = 1680,
                            Year = 2020,
                            ZeroToHundred = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Subaru",
                            Drivetrain = "AWD",
                            DrivingStyle = 1,
                            EngineType = "2.0 Turbo",
                            HorsePower = 268,
                            Model = "WRX",
                            Torque = 350,
                            UserId = "b8c7553d-0b10-454f-8d1c-6cbf165168ff",
                            Weight = 1500,
                            Year = 2019,
                            ZeroToHundred = 0.0
                        });
                });

            modelBuilder.Entity("AutoTuner.Models.PerformanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewPower")
                        .HasColumnType("int");

                    b.Property<int>("NewTorque")
                        .HasColumnType("int");

                    b.Property<int>("OldPower")
                        .HasColumnType("int");

                    b.Property<int>("OldTorque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("PerformanceHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            DateApplied = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewPower = 245,
                            NewTorque = 370,
                            OldPower = 230,
                            OldTorque = 350
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            DateApplied = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewPower = 473,
                            NewTorque = 550,
                            OldPower = 430,
                            OldTorque = 500
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            DateApplied = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewPower = 268,
                            NewTorque = 350,
                            OldPower = 250,
                            OldTorque = 330
                        });
                });

            modelBuilder.Entity("AutoTuner.Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeSafetyParts")
                        .HasColumnType("bit");

                    b.Property<int>("PredictedPower")
                        .HasColumnType("int");

                    b.Property<int>("PredictedTorque")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TuningPartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("TuningPartId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("AutoTuner.Models.TuningPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("EfficiencyImpact")
                        .HasColumnType("float");

                    b.Property<bool>("IsSafetyCritical")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PowerGain")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedForStyle")
                        .HasColumnType("int");

                    b.Property<int>("TorqueGain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TuningParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Intake",
                            Cost = 450m,
                            Description = "High flow intake system for improved airflow.",
                            EfficiencyImpact = 2.5,
                            IsSafetyCritical = false,
                            Name = "Performance Air Intake",
                            PowerGain = 15,
                            RecommendedForStyle = 1,
                            TorqueGain = 12
                        },
                        new
                        {
                            Id = 2,
                            Category = "Exhaust",
                            Cost = 980m,
                            Description = "Cat-back exhaust for enhanced sound and flow.",
                            EfficiencyImpact = 1.5,
                            IsSafetyCritical = false,
                            Name = "Sport Exhaust",
                            PowerGain = 20,
                            RecommendedForStyle = 1,
                            TorqueGain = 18
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Cost = 650m,
                            Description = "Software tune optimized for premium fuel.",
                            EfficiencyImpact = -1.0,
                            IsSafetyCritical = false,
                            Name = "ECU Tune Stage 1",
                            PowerGain = 40,
                            RecommendedForStyle = 0,
                            TorqueGain = 60
                        },
                        new
                        {
                            Id = 4,
                            Category = "Chassis",
                            Cost = 1200m,
                            Description = "Forged wheels reducing unsprung mass.",
                            EfficiencyImpact = 3.5,
                            IsSafetyCritical = false,
                            Name = "Lightweight Wheels",
                            PowerGain = 0,
                            RecommendedForStyle = 0,
                            TorqueGain = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fuel",
                            Cost = 750m,
                            Description = "Supports higher boost levels with consistent fuel delivery.",
                            EfficiencyImpact = -2.0,
                            IsSafetyCritical = false,
                            Name = "High-Flow Fuel Pump",
                            PowerGain = 25,
                            RecommendedForStyle = 1,
                            TorqueGain = 28
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Cost = 300m,
                            Description = "Economy focused tune for better mileage.",
                            EfficiencyImpact = 6.0,
                            IsSafetyCritical = false,
                            Name = "Eco Driving Chip",
                            PowerGain = 5,
                            RecommendedForStyle = 2,
                            TorqueGain = 8
                        },
                        new
                        {
                            Id = 7,
                            Category = "Brakes",
                            Cost = 1100m,
                            Description = "Six-piston calipers with semi-slick pads for confident stopping power.",
                            EfficiencyImpact = -0.5,
                            IsSafetyCritical = true,
                            Name = "Performance Brake Kit",
                            PowerGain = 0,
                            RecommendedForStyle = 1,
                            TorqueGain = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = "Suspension",
                            Cost = 1400m,
                            Description = "Height and damping adjustable coilovers tuned for spirited driving.",
                            EfficiencyImpact = 2.0,
                            IsSafetyCritical = true,
                            Name = "Adjustable Coilover Suspension",
                            PowerGain = 0,
                            RecommendedForStyle = 1,
                            TorqueGain = 5
                        });
                });

            modelBuilder.Entity("AutoTuner.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Speed Ave",
                            City = "Sofia",
                            Latitude = 42.697699999999998,
                            Longitude = 23.321899999999999,
                            Name = "Turbo Masters",
                            Specialization = "Forced Induction"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Track St",
                            City = "Plovdiv",
                            Latitude = 42.135399999999997,
                            Longitude = 24.7453,
                            Name = "Precision Tuners",
                            Specialization = "ECU Calibration"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Green Blvd",
                            City = "Varna",
                            Latitude = 43.214100000000002,
                            Longitude = 27.9147,
                            Name = "EcoDrive Labs",
                            Specialization = "Hybrid & Economy"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b8c7553d-0b10-454f-8d1c-6cbf165168ff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "DEMO-CONCURRENCY-STAMP",
                            Email = "demo@autotuner.ai",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMO@AUTOTUNER.AI",
                            NormalizedUserName = "DEMO@AUTOTUNER.AI",
                            PasswordHash = "AQEAAAAQJwAAEAAAAD0vHIqbDU5vESIzRFVmd4ggAAAAJMotm0/c8s7LQD6BsIbVrk5VdXVsXfA/pffr8XvOroU=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "DEMO-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "demo@autotuner.ai"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoTuner.Models.Car", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutoTuner.Models.PerformanceHistory", b =>
                {
                    b.HasOne("AutoTuner.Models.Car", "Car")
                        .WithMany("PerformanceHistory")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoTuner.Models.Recommendation", b =>
                {
                    b.HasOne("AutoTuner.Models.Car", "Car")
                        .WithMany("Recommendations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoTuner.Models.TuningPart", "TuningPart")
                        .WithMany("Recommendations")
                        .HasForeignKey("TuningPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("TuningPart");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoTuner.Models.Car", b =>
                {
                    b.Navigation("PerformanceHistory");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("AutoTuner.Models.TuningPart", b =>
                {
                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
